### ISSUE TITLE
API challenges documentation - missing expected response for some challenges

### ISSUE THREAD

**Issue by p2635** [eviltester/thingifier#23]
Link: https://apichallenges.herokuapp.com/gui/challenges/

Some challenges are missing the expected response code:

- 31
- 32
- 34-40

**Example**
For example, 31 and 32 here do not have something like 33 (`POST /todos` (415))
<img width="600" alt="image" src="https://github.com/eviltester/thingifier/assets/4522927/6c128dd6-69fb-4469-a8e6-fbf605712795">

**Comment by eviltester** [comment]
Thanks. I intended those to be summaries of the challenge, rather than the full details. It would probably have been easier if I hadn't put any status codes in the title.

I agree it can look inconsistent, but I probably won't amend it. I might amend the description summaries to cover this though. So thanks for pointing it out.
